all files removed are built & placed in sbin automatically. removed busybox,toolbox,toybox. now to fix install errors & removal of busybox errors use TW_USE_TOOLBOX := tru$ added use TW_NO_LEGACY_PROPS := true added commits to bootable recovery that relate to changes. Fix build error on Pie with TW_NO_LEGACY_PROPS := true
Fixes:
bootable/recovery/twinstall.cpp:83:12: error: unused function 'switch_to_legacy$
static int switch_to_legacy_properties()
           ^
bootable/recovery/twinstall.cpp:110:12: error: unused function 'switch_to_new_p$
static int switch_to_new_properties()
           ^
bootable/recovery/twinstall.cpp:176:13: error: unused function 'update_binary_h$
static bool update_binary_has_legacy_properties(const char *binary) {
https://gerrit.omnirom.org/#/c/android_bootable_recovery/+/32482/

https://gerrit.omnirom.org/#/c/android_bootable_recovery/+/32648/